version: "3.9"

services:
  login-api:
    build:
      context: .
      dockerfile: Login.Api/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Debug}
    networks:
      - listive-network

networks:
  listive-network:
    name: listive-network